name: Notify changes

on: 
  push:
    branches:
      master

jobs:
  notify_job:
    runs-on: ubuntu-latest
    steps:
      - name: Docker action
        uses: rasmusebbesen/action-notify@master
        with:
          trigger: ${GITHUB_REPOSITORY}

